# Generated by Django 5.1.4 on 2025-01-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='description',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
