# Generated by Django 5.1.4 on 2025-01-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='schedule',
            field=models.TextField(blank=True),
        ),
    ]
