# Generated by Django 5.1.4 on 2025-01-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_retreat_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='zoom_link',
            field=models.URLField(blank=True),
        ),
    ]
