# Generated by Django 5.1.4 on 2025-01-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_retreat_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='retreat_image',
            field=models.URLField(default='https://vh1220.z2systems.com/neon/resource/vh1220/images/buddhalei3(2).JPG'),
        ),
    ]
