# Generated by Django 5.1.4 on 2025-02-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_retreat_retreat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='announcement',
            field=models.TextField(blank=True),
        ),
    ]
