# Generated by Django 5.1.4 on 2025-02-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_retreat_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='recording')),
                ('recording_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='retreat',
            name='recordings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.recording'),
        ),
    ]
