# Generated by Django 5.1.4 on 2025-02-28 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_remove_retreat_recordings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='retreat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.retreat'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='time',
            field=models.DateTimeField(verbose_name='recording_time'),
        ),
    ]
