# Generated by Django 5.1.4 on 2025-04-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_recording_retreat_alter_recording_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resoruce_link', models.URLField()),
                ('retreat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.retreat')),
            ],
        ),
    ]
